// src/routes/Explorer.svelte
<script lang="ts">
  import { link } from 'svelte-spa-router';
  import { language, t, tl } from '../stores/language';
  import { ui } from '../stores/ui';
  import { udlData } from '../stores/udlData';
  import { 
    searchResults, 
    searchQuery, 
    selectedPrinciple, 
    selectedGuideline,
    selectedConsideration,
    selectedEducationalLevel,
    selectedCurricularArea,
    selectedType, 
    availableGuidelines,
    availableConsiderations,
    availableEducationalLevels,
    availableCurricularAreas,
    resetFilters 
  } from '../stores/search';
  import LanguageSwitcher from '../components/LanguageSwitcher.svelte';
  import SearchBar from '../components/SearchBar.svelte';
  import Tag from '../components/Tag.svelte';
  import { ArrowLeft, Filter } from 'lucide-svelte';
  import { getGuidelineStyles } from '../utils/colors';
  import LevelBadge from '../components/model/LevelBadge.svelte';
  import type { Language, SearchResult } from '../types';
  import FloatingNavigation from '../components/FloatingNavigation.svelte';
  import Breadcrumbs from '../components/Breadcrumbs.svelte';
  import { Home, Search } from 'lucide-svelte';

  let currentLang: Language;
  language.subscribe((value) => {
    currentLang = value;
  });

  // Cascading logic: Reset dependent filters when parent changes
  $: if ($selectedPrinciple) {
    selectedGuideline.set('all');
    selectedConsideration.set('all');
  }

  $: if ($selectedGuideline) {
    selectedConsideration.set('all');
  }

  function getPrincipleForResult(result: SearchResult) {
    return $udlData.networks.find((n) => n.principle.id === result.principleId)?.principle;
  }

  function getDisplayText(result: SearchResult): string {
    if (result.type === 'principle' && 'name' in result.item) {
      return t(result.item.name, currentLang);
    } else if (result.type === 'guideline' && 'name' in result.item) {
      return t(result.item.name, currentLang);
    } else if (result.type === 'consideration' && 'description' in result.item) {
      return t(result.item.description, currentLang);
    } else if (result.type === 'activity' && 'title' in result.item) {
      return t(result.item.title, currentLang);
    }
    return '';
  }

  function getItemLink(result: SearchResult): string {
    if (result.type === 'example') {
      return `/detail/${result.considerationId}`;
    } else if (result.type === 'activity') {
      return `/detail/${result.id}`;
    } else if (result.type === 'consideration' || result.type === 'guideline' || result.type === 'principle') {
      return `/detail/${result.id}`;
    } else {
      return `/model`;
    }
  }

  // Breadcrumbs
  $: breadcrumbItems = [
    { label: '', href: '/', icon: Home },
    { label: $ui.searchAction, icon: Search }
  ];
</script>

<div class="min-h-screen bg-gray-50">
  <!-- Header -->
  <div class="bg-white border-b border-gray-200 sticky top-0 z-20 shadow-sm">
    <div class="container mx-auto px-4 py-4">
      <div class="flex items-center justify-between">
        <div class="flex-1 min-w-0 mr-4">
           <Breadcrumbs items={breadcrumbItems} />
        </div>
        <LanguageSwitcher />
      </div>
    </div>
  </div>
  
  <div class="flex justify-center mt-8">
    <SearchBar />
  </div>

  <!-- Filters -->
  <div class="bg-white border-b border-gray-200 py-4 mt-8">
    <div class="container mx-auto px-4">
      <div class="flex items-center gap-4 flex-wrap">
        <div class="flex items-center gap-2">
          <Filter class="w-5 h-5 text-gray-600" />
          <span class="text-sm font-medium text-gray-700">{$ui.filters}:</span>
        </div>

        <!-- Principle Filter -->
        <select
          bind:value={$selectedPrinciple}
          class="px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
        >
          <option value="all">{$ui.allPrinciples}</option>
          {#each $udlData.networks as network}
            <option value={network.principle.id}>{t(network.principle.name, currentLang)}</option>
          {/each}
        </select>

        <!-- Guideline Filter (Cascading) -->
        <select
          bind:value={$selectedGuideline}
          class="px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
        >
          <option value="all">{$ui.allGuidelines || 'Todas las pautas'}</option>
          {#each $availableGuidelines as guideline}
            <option value={guideline.id}>{guideline.code}: {t(guideline.name, currentLang)}</option>
          {/each}
        </select>

        <!-- Consideration Filter (Cascading) -->
        <select
          bind:value={$selectedConsideration}
          class="px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 max-w-xs"
        >
          <option value="all">{$ui.allConsiderations || 'Todas las consideraciones'}</option>
          {#each $availableConsiderations as consideration}
            <option value={consideration.id}>{consideration.code}: {t(consideration.description, currentLang).substring(0, 50)}...</option>
          {/each}
        </select>

        <!-- Type Filter -->
        <select
          bind:value={$selectedType}
          class="px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
        >
          <option value="all">{$ui.allTypes}</option>
          <option value="guideline">{$ui.guidelines}</option>
          <option value="consideration">{$ui.considerations}</option>
          <option value="activity">{$ui.activity || 'Actividad'}</option>
          <option value="example">{$ui.examples}</option>
        </select>

        {#if $selectedType === 'example' || $selectedType === 'activity' || $selectedType === 'all'}
          <!-- Educational Level Filter -->
          <select
            bind:value={$selectedEducationalLevel}
            class="px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
          >
            <option value="all">{$ui.allEducationalLevels}</option>
            {#each $availableEducationalLevels as level}
              <option value={level.es}>{t(level, currentLang)}</option>
            {/each}
          </select>

          <!-- Curricular Area Filter -->
          <select
            bind:value={$selectedCurricularArea}
            class="px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
          >
            <option value="all">{$ui.allCurricularAreas}</option>
            {#each $availableCurricularAreas as area}
              <option value={area.es}>{t(area, currentLang)}</option>
            {/each}
          </select>
        {/if}

        {#if $searchQuery || $selectedPrinciple !== 'all' || $selectedGuideline !== 'all' || $selectedConsideration !== 'all' || $selectedType !== 'all' || $selectedEducationalLevel !== 'all' || $selectedCurricularArea !== 'all'}
          <button
            on:click={resetFilters}
            class="text-sm text-blue-600 hover:text-blue-800 font-medium"
          >
            {$ui.clearFilters}
          </button>
        {/if}
      </div>
    </div>
  </div>

  <!-- Results -->
  <div class="container mx-auto px-4 py-8">
    <div class="mb-4 text-sm text-gray-600">
      {$searchResults.length} {$searchResults.length !== 1 ? $ui.results : $ui.result}
    </div>

    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
      {#each $searchResults as result}
        {@const principle = getPrincipleForResult(result)}
        {@const guideline = result.type === 'consideration' || result.type === 'guideline' 
          ? $udlData.networks
              .flatMap(n => n.principle.guidelines)
              .find(g => g.id === result.guidelineId || g.code === result.code.split('.')[0])
          : null}
        {@const styles = guideline ? getGuidelineStyles(guideline) : null}
        <a
          href={getItemLink(result)}
          use:link
          class="block bg-white p-6 rounded-xl shadow-sm hover:shadow-xl border border-gray-100 transition-all duration-300 hover:-translate-y-1 group"
          style="border-top: 4px solid {principle?.color || '#eee'}; {styles?.bgLight || ''}"
        >
          <div class="flex items-start justify-between mb-2">
            {#if result.type === 'activity' || result.code}
              <span class="font-mono text-lg font-bold" style="{styles?.text || 'color: #374151'}">
                {result.code}
              </span>
            {:else if result.type === 'example'}
              <div class="flex flex-col gap-1">
                <span class="font-mono text-xs font-black" style="color: {result.item.color}">
                  {result.item.code}
                </span>
              </div>
            {/if}
            
            <div class="flex flex-col items-end gap-1">
               <span class="text-[10px] px-2 py-0.5 font-black uppercase tracking-wider rounded border" 
                     style="background-color: white; border-color: {principle?.color || '#eee'}; color: {principle?.color || '#666'}">
                 {#if result.type === 'principle'}
                   {$ui.principle || 'Principio'}
                 {:else if result.type === 'guideline'}
                   {$ui.guideline || 'Pauta'}
                 {:else if result.type === 'consideration'}
                   {$ui.consideration || 'Consideración'}
                 {:else if result.type === 'activity'}
                   {$ui.activity || 'Actividad'}
                 {:else}
                   {$ui.examples || 'Ejemplo'}
                 {/if}
               </span>
               
               {#if result.type === 'activity' || result.type === 'example'}
                 <div class="flex gap-1">
                    <span class="text-[8px] px-1.5 py-0.5 font-black uppercase tracking-wider rounded bg-blue-50 text-blue-600 border border-blue-100">
                     {t(result.educationalLevel, currentLang)}
                   </span>
                   <span class="text-[8px] px-1.5 py-0.5 font-black uppercase tracking-wider rounded bg-purple-50 text-purple-600 border border-purple-100">
                     {t(result.curricularArea, currentLang)}
                   </span>
                 </div>
               {/if}
            </div>
          </div>
          
          <p class="font-bold {(!result.item?.designOptions && result.type === 'example') ? '' : 'mb-3'}" style="color: {principle?.color || '#111827'}">
            {result.type === 'example' ? t(result.item.activity, currentLang) : getDisplayText(result)}
          </p>

          {#if result.type === 'example' && result.item.designOptions}
            <div class="mb-3 text-sm text-gray-600 line-clamp-2">
              {#each tl(result.item.designOptions, currentLang) as paragraph}
                <span>{paragraph} </span>
              {/each}
            </div>
          {/if}

          {#if result.type === 'example' && result.item.webTools && result.item.webTools.length > 0}
            <div class="flex flex-wrap gap-2 mb-3">
              {#each result.item.webTools as tool}
                <div class="flex items-center gap-1.5 px-2 py-1 bg-gray-50 rounded-lg border border-gray-100 transition-colors">
                  {#if tool.logo}
                    <img src={tool.logo} alt="" class="w-3.5 h-3.5 object-contain" on:error={(e) => { if (e.currentTarget instanceof HTMLImageElement) e.currentTarget.style.display = 'none'; }} />
                  {/if}
                  <span class="text-[10px] font-bold text-gray-700">{tool.name}</span>
                </div>
              {/each}
            </div>
          {/if}
          
          <div class="flex items-center justify-between mt-3">
            {#if principle?.color}
              <Tag color={principle.color} label={t(principle.name, currentLang)} small={true} />
            {:else if result.type === 'example'}
               <span class="text-[10px] font-bold text-gray-400">ID: {result.considerationId}</span>
            {:else if result.type === 'activity'}
               <span class="text-[10px] font-bold text-gray-400">Full View</span>
            {/if}
            
            {#if guideline}
              <LevelBadge row={guideline.row} {currentLang} />
            {/if}
          </div>
        </a>
      {/each}
    </div>

    {#if $searchResults.length === 0}
      <div class="text-center py-12">
        <p class="text-gray-500 text-lg">{$ui.noResults}</p>
        <button
          on:click={resetFilters}
          class="mt-4 text-blue-600 hover:text-blue-800 font-medium"
        >
          {$ui.clearFilters}
        </button>
      </div>
    {/if}
    <FloatingNavigation currentPage="explorer" />
  </div>
</div>

// src/routes/Explorer.tsx
import { useMemo, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { useLanguage } from '../contexts/LanguageContext';
import { useUI } from '../contexts/UIContext';
import { useUDLData } from '../contexts/UDLDataContext';
import { useSearch } from '../contexts/SearchContext';
import LanguageSwitcher from '../components/LanguageSwitcher';
import SearchBar from '../components/SearchBar';
import Tag from '../components/Tag';
import LevelBadge from '../components/model/LevelBadge';
import FloatingNavigation from '../components/FloatingNavigation';
import Breadcrumbs from '../components/Breadcrumbs';
import { Home, Search, Filter } from 'lucide-react';
import { getGuidelineStyles } from '../utils/colors';
import type { SearchResult } from '../types';

export default function Explorer() {
  const { t, tl } = useLanguage();
  const ui = useUI();
  const { udlData } = useUDLData();
  const {
    searchResults,
    searchQuery,
    selectedPrinciple,
    setSelectedPrinciple,
    selectedGuideline,
    setSelectedGuideline,
    selectedConsideration,
    setSelectedConsideration,
    selectedEducationalLevel,
    setSelectedEducationalLevel,
    selectedCurricularArea,
    setSelectedCurricularArea,
    selectedType,
    setSelectedType,
    availableGuidelines,
    availableConsiderations,
    availableEducationalLevels,
    availableCurricularAreas,
    resetFilters,
  } = useSearch();

  // Cascading logic: Reset dependent filters when parent changes
  useEffect(() => {
    if (selectedPrinciple !== 'all') {
      setSelectedGuideline('all');
      setSelectedConsideration('all');
    }
  }, [selectedPrinciple]);

  useEffect(() => {
    if (selectedGuideline !== 'all') {
      setSelectedConsideration('all');
    }
  }, [selectedGuideline]);

  const breadcrumbItems = useMemo(
    () => [
      { label: '', href: '/', icon: Home },
      { label: ui.searchAction, icon: Search },
    ],
    [ui.searchAction]
  );

  const getPrincipleForResult = (result: SearchResult) => {
    return udlData.networks.find((n) => n.principle.id === result.principleId)?.principle;
  };

  const getDisplayText = (result: SearchResult): string => {
    if (result.type === 'principle' && 'name' in result.item) {
      return t(result.item.name);
    } else if (result.type === 'guideline' && 'name' in result.item) {
      return t(result.item.name);
    } else if (result.type === 'consideration' && 'description' in result.item) {
      return t(result.item.description);
    } else if (result.type === 'activity' && 'title' in result.item) {
      return t(result.item.title);
    }
    return '';
  };

  const getItemLink = (result: SearchResult): string => {
    if (result.type === 'example') {
      return `/detail/${result.considerationId}`;
    } else if (result.type === 'activity') {
      return `/detail/${result.id}`;
    } else if (['consideration', 'guideline', 'principle'].includes(result.type)) {
      return `/detail/${result.id}`;
    }
    return '/model';
  };

  const hasActiveFilters =
    searchQuery ||
    selectedPrinciple !== 'all' ||
    selectedGuideline !== 'all' ||
    selectedConsideration !== 'all' ||
    selectedType !== 'all' ||
    selectedEducationalLevel !== 'all' ||
    selectedCurricularArea !== 'all';

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <div className="bg-white border-b border-gray-200 sticky top-0 z-20 shadow-sm">
        <div className="container mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <div className="flex-1 min-w-0 mr-4">
              <Breadcrumbs items={breadcrumbItems} />
            </div>
            <LanguageSwitcher />
          </div>
        </div>
      </div>

      <div className="flex justify-center mt-8">
        <SearchBar />
      </div>

      {/* Filters */}
      <div className="bg-white border-b border-gray-200 py-4 mt-8">
        <div className="container mx-auto px-4">
          <div className="flex items-center gap-4 flex-wrap">
            <div className="flex items-center gap-2">
              <Filter className="w-5 h-5 text-gray-600" />
              <span className="text-sm font-medium text-gray-700">{ui.filters}:</span>
            </div>

            {/* Principle Filter */}
            <select
              value={selectedPrinciple}
              onChange={(e) => setSelectedPrinciple(e.target.value)}
              className="px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
            >
              <option value="all">{ui.allPrinciples}</option>
              {udlData.networks.map((network) => (
                <option key={network.principle.id} value={network.principle.id}>
                  {t(network.principle.name)}
                </option>
              ))}
            </select>

            {/* Guideline Filter */}
            <select
              value={selectedGuideline}
              onChange={(e) => setSelectedGuideline(e.target.value)}
              className="px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
            >
              <option value="all">{ui.allGuidelines || 'Todas las pautas'}</option>
              {availableGuidelines.map((guideline) => (
                <option key={guideline.id} value={guideline.id}>
                  {guideline.code}: {t(guideline.name)}
                </option>
              ))}
            </select>

            {/* Consideration Filter */}
            <select
              value={selectedConsideration}
              onChange={(e) => setSelectedConsideration(e.target.value)}
              className="px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 max-w-xs"
            >
              <option value="all">{ui.allConsiderations || 'Todas las consideraciones'}</option>
              {availableConsiderations.map((consideration) => (
                <option key={consideration.id} value={consideration.id}>
                  {consideration.code}: {t(consideration.description).substring(0, 50)}...
                </option>
              ))}
            </select>

            {/* Type Filter */}
            <select
              value={selectedType}
              onChange={(e) => setSelectedType(e.target.value as typeof selectedType)}
              className="px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
            >
              <option value="all">{ui.allTypes}</option>
              <option value="guideline">{ui.guidelines}</option>
              <option value="consideration">{ui.considerations}</option>
              <option value="activity">{ui.activity || 'Actividad'}</option>
              <option value="example">{ui.examples}</option>
            </select>

            {(selectedType === 'example' ||
              selectedType === 'activity' ||
              selectedType === 'all') && (
              <>
                {/* Educational Level Filter */}
                <select
                  value={selectedEducationalLevel}
                  onChange={(e) => setSelectedEducationalLevel(e.target.value)}
                  className="px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                >
                  <option value="all">{ui.allEducationalLevels}</option>
                  {availableEducationalLevels.map((level) => (
                    <option key={level.es} value={level.es}>
                      {t(level)}
                    </option>
                  ))}
                </select>

                {/* Curricular Area Filter */}
                <select
                  value={selectedCurricularArea}
                  onChange={(e) => setSelectedCurricularArea(e.target.value)}
                  className="px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                >
                  <option value="all">{ui.allCurricularAreas}</option>
                  {availableCurricularAreas.map((area) => (
                    <option key={area.es} value={area.es}>
                      {t(area)}
                    </option>
                  ))}
                </select>
              </>
            )}

            {hasActiveFilters && (
              <button
                onClick={resetFilters}
                className="text-sm text-blue-600 hover:text-blue-800 font-medium"
              >
                {ui.clearFilters}
              </button>
            )}
          </div>
        </div>
      </div>

      {/* Results */}
      <div className="container mx-auto px-4 py-8">
        <div className="mb-4 text-sm text-gray-600">
          {searchResults.length} {searchResults.length !== 1 ? ui.results : ui.result}
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {searchResults.map((result) => {
            const principle = getPrincipleForResult(result);
            const guideline =
              result.type === 'consideration' || result.type === 'guideline'
                ? udlData.networks
                    .flatMap((n) => n.principle.guidelines)
                    .find(
                      (g) => g.id === result.guidelineId || g.code === result.code?.split('.')[0]
                    )
                : null;
            const styles = guideline ? getGuidelineStyles(guideline) : null;

            return (
              <Link
                key={result.id}
                to={getItemLink(result)}
                className="block bg-white p-6 rounded-xl shadow-sm hover:shadow-xl border border-gray-100 transition-all duration-300 hover:-translate-y-1 group"
                style={{
                  borderTop: `4px solid ${principle?.color || '#eee'}`,
                  backgroundColor: styles
                    ? `rgba(${parseInt((principle?.color || '#eee').slice(1, 3), 16)}, ${parseInt((principle?.color || '#eee').slice(3, 5), 16)}, ${parseInt((principle?.color || '#eee').slice(5, 7), 16)}, 0.05)`
                    : undefined,
                }}
              >
                <div className="flex items-start justify-between mb-2">
                  {(result.type === 'activity' || result.code) && (
                    <span
                      className="font-mono text-lg font-bold"
                      style={{ color: styles?.hex || '#374151' }}
                    >
                      {result.code}
                    </span>
                  )}
                  {result.type === 'example' && (
                    <div className="flex flex-col gap-1">
                      <span
                        className="font-mono text-xs font-black"
                        style={{ color: result.item.color }}
                      >
                        {result.item.code}
                      </span>
                    </div>
                  )}

                  <div className="flex flex-col items-end gap-1">
                    <span
                      className="text-[10px] px-2 py-0.5 font-black uppercase tracking-wider rounded border"
                      style={{
                        backgroundColor: 'white',
                        borderColor: principle?.color || '#eee',
                        color: principle?.color || '#666',
                      }}
                    >
                      {result.type === 'principle' && (ui.principle || 'Principio')}
                      {result.type === 'guideline' && (ui.guideline || 'Pauta')}
                      {result.type === 'consideration' && (ui.consideration || 'Consideración')}
                      {result.type === 'activity' && (ui.activity || 'Actividad')}
                      {result.type === 'example' && (ui.examples || 'Ejemplo')}
                    </span>

                    {(result.type === 'activity' || result.type === 'example') && (
                      <div className="flex gap-1">
                        <span className="text-[8px] px-1.5 py-0.5 font-black uppercase tracking-wider rounded border bg-gray-100 text-gray-700 border-gray-200">
                          {t(result.educationalLevel)}
                        </span>
                        <span className="text-[8px] px-1.5 py-0.5 font-black uppercase tracking-wider rounded border bg-gray-100 text-gray-700 border-gray-200">
                          {t(result.curricularArea)}
                        </span>
                      </div>
                    )}
                  </div>
                </div>

                <p
                  className={`font-bold ${!result.item?.designOptions && result.type === 'example' ? '' : 'mb-3'}`}
                  style={{ color: principle?.color || '#111827' }}
                >
                  {result.type === 'example' ? t(result.item.activity) : getDisplayText(result)}
                </p>

                {result.type === 'example' && result.item.designOptions && (
                  <div className="mb-3 text-sm text-gray-600 line-clamp-2">
                    {tl(result.item.designOptions).map((paragraph, i) => (
                      <span key={i}>{paragraph} </span>
                    ))}
                  </div>
                )}

                {result.type === 'example' &&
                  result.item.webTools &&
                  result.item.webTools.length > 0 && (
                    <div className="flex flex-wrap gap-2">
                      {result.item.webTools?.map((tool: any, i: number) => (
                        <div
                          key={i}
                          className="flex items-center gap-1.5 px-2 py-1 bg-gray-50 rounded-lg border border-gray-100 transition-colors"
                        >
                          {tool.logo && (
                            <img
                              src={tool.logo}
                              alt=""
                              className="w-3.5 h-3.5 object-contain"
                              onError={(e) => {
                                e.currentTarget.style.display = 'none';
                              }}
                            />
                          )}
                          <span className="text-[10px] font-bold text-gray-700">{tool.name}</span>
                        </div>
                      ))}
                    </div>
                  )}

                <div className="flex items-center justify-between mt-3">
                  {principle?.color ? (
                    <Tag color={principle.color} label={t(principle.name)} small={true} />
                  ) : result.type === 'example' ? (
                    <span className="text-[10px] font-bold text-gray-400">
                      ID: {result.considerationId}
                    </span>
                  ) : result.type === 'activity' ? (
                    <span className="text-[10px] font-bold text-gray-400">Full View</span>
                  ) : null}

                  {guideline && <LevelBadge row={guideline.row} />}
                </div>
              </Link>
            );
          })}
        </div>

        {searchResults.length === 0 && (
          <div className="text-center py-12">
            <p className="text-gray-500 text-lg">{ui.noResults}</p>
            <button
              onClick={resetFilters}
              className="mt-4 text-blue-600 hover:text-blue-800 font-medium"
            >
              {ui.clearFilters}
            </button>
          </div>
        )}
        <FloatingNavigation currentPage="explorer" />
      </div>
    </div>
  );
}
