// src/components/LanguageSwitcher.tsx
import { useLanguage } from '../contexts/LanguageContext';
import type { Language } from '../types';

const languages: { code: Language; label: string }[] = [
  { code: 'es', label: 'ES' },
  { code: 'en', label: 'EN' },
  { code: 'eu', label: 'EU' },
  { code: 'la', label: 'LA' },
];

export default function LanguageSwitcher() {
  const { language, setLanguage } = useLanguage();

  return (
    <div className="flex gap-2 bg-white rounded-full shadow-md p-1">
      {languages.map((lang) => (
        <button
          key={lang.code}
          onClick={() => setLanguage(lang.code)}
          className={`px-4 py-2 rounded-full font-bold text-sm transition-all ${
            language === lang.code ? 'bg-gray-900 text-white' : 'text-gray-600 hover:bg-gray-100'
          }`}
        >
          {lang.label}
        </button>
      ))}
    </div>
  );
}

// src/components/LanguageSwitcher.svelte
<script lang="ts">
  import { language } from '../stores/language';
  import type { Language } from '../types';
  import { Globe } from 'lucide-svelte';

  const languages: { code: Language; label: string }[] = [
    { code: 'es', label: 'Español' },
    { code: 'eu', label: 'Euskara' },
    { code: 'en', label: 'English' },
    { code: 'la', label: 'Latina' },
  ];

  let currentLang: Language;
  language.subscribe((value) => {
    currentLang = value;
  });

  function setLanguage(lang: Language) {
    language.set(lang);
  }
</script>

<div class="flex items-center gap-2">
  <Globe class="w-5 h-5 text-gray-600" />
  <div class="flex gap-1 bg-gray-100 rounded-lg p-1">
    {#each languages as lang}
      <button
        class="px-3 py-1 rounded-md text-sm font-medium transition-all {currentLang === lang.code
          ? 'bg-white text-gray-900 shadow-sm'
          : 'text-gray-600 hover:text-gray-900'}"
        on:click={() => setLanguage(lang.code)}
      >
        {lang.label}
      </button>
    {/each}
  </div>
</div>
