// src/components/MarkdownRenderer.svelte
<script lang="ts">
  import { Markdown } from 'svelte-exmarkdown';

  export let content: string;
</script>

<div class="prose prose-sm max-w-none">
  <Markdown md={content} />
</div>

<style>
  :global(.prose) {
    color: inherit;
  }
  :global(.prose p) {
    margin-bottom: 0.5em;
  }
  :global(.prose ul) {
    margin-top: 0.5em;
  }
</style>

// src/components/MarkdownRenderer.tsx
import ReactMarkdown from 'react-markdown';

interface MarkdownRendererProps {
  content: string;
}

export default function MarkdownRenderer({ content }: MarkdownRendererProps) {
  return (
    <div className="prose prose-sm max-w-none markdown-content">
      <ReactMarkdown>{content}</ReactMarkdown>
      <style jsx>{`
        :global(.markdown-content) {
          color: inherit;
        }
        :global(.markdown-content p) {
          margin-bottom: 0.5em;
        }
        :global(.markdown-content ul) {
          margin-top: 0.5em;
        }
      `}</style>
    </div>
  );
}
